[2017-08-09 11:14:51.620] [ERROR] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 11:14:51.621] [FATAL] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 11:14:52.439] [ERROR] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 11:14:52.439] [FATAL] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 15:26:22.125] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/agentRegister","message":"Redis connection lost and command aborted. It might have been processed.","stack":"AbortError: Redis connection lost and command aborted. It might have been processed.\n    at RedisClient.flush_and_error (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\redis\\index.js:350:23)\n    at RedisClient.connection_gone (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\redis\\index.js:652:14)\n    at RedisClient.on_error (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\redis\\index.js:398:10)\n    at Socket.<anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\redis\\index.js:272:14)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1272:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)"}}
[2017-08-09 15:26:40.095] [ERROR] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 15:26:40.096] [FATAL] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 15:27:36.276] [ERROR] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 15:27:36.276] [FATAL] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 16:07:07.600] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\base\\head.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\base\\head.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:07:09.933] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\base\\head.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\base\\head.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:07:47.431] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\base\\head.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\base\\head.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:07:48.030] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:07:48.515] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:07:48.727] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:07:48.917] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:07:49.101] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:07:54.746] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:08:10.897] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:08:11.392] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:08:11.895] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:08:12.074] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:08:12.251] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:08:12.411] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:08:12.585] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:08:12.758] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:08:12.930] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:08:13.117] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:08:13.276] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:09:42.498] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:09:43.022] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:09:43.538] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:09:43.744] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:09:43.927] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:09:44.106] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:09:44.283] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:09:51.207] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'","stack":"Error: ENOENT: no such file or directory, open 'D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\side.ejs'\n    at Error (native)\n    at Object.fs.openSync (fs.js:634:18)\n    at Object.fs.readFileSync (fs.js:502:33)\n    at includeSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:210:17)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:569:26\n    at Array.forEach (native)\n    at Object.Template.generateSource (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:545:15)\n    at Object.Template.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:450:12)\n    at Object.compile (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:306:16)\n    at handleCache (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:169:18)"}}
[2017-08-09 16:09:52.730] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined","stack":"ReferenceError: D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:174:16)\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:325:10)\n    at returnedFn (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:520:17)\n    at View.exports.renderFile [as engine] (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:374:31)\n    at View.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\view.js:126:8)\n    at tryRender (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:639:10)\n    at EventEmitter.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:591:3)\n    at ServerResponse.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\response.js:960:7)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\routes\\web\\login\\index.js:120:20\n    at request.callback (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\service\\login\\index.js:150:17)"}}
[2017-08-09 16:09:53.580] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined","stack":"ReferenceError: D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:174:16)\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:325:10)\n    at returnedFn (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:520:17)\n    at View.exports.renderFile [as engine] (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:374:31)\n    at View.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\view.js:126:8)\n    at tryRender (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:639:10)\n    at EventEmitter.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:591:3)\n    at ServerResponse.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\response.js:960:7)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\routes\\web\\login\\index.js:120:20\n    at request.callback (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\service\\login\\index.js:150:17)"}}
[2017-08-09 16:10:39.095] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined","stack":"ReferenceError: D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:174:16)\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:325:10)\n    at returnedFn (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:520:17)\n    at View.exports.renderFile [as engine] (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:374:31)\n    at View.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\view.js:126:8)\n    at tryRender (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:639:10)\n    at EventEmitter.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:591:3)\n    at ServerResponse.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\response.js:960:7)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\routes\\web\\login\\index.js:120:20\n    at request.callback (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\service\\login\\index.js:150:17)"}}
[2017-08-09 16:10:39.745] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined","stack":"ReferenceError: D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:174:16)\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:325:10)\n    at returnedFn (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:520:17)\n    at View.exports.renderFile [as engine] (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:374:31)\n    at View.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\view.js:126:8)\n    at tryRender (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:639:10)\n    at EventEmitter.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:591:3)\n    at ServerResponse.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\response.js:960:7)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\routes\\web\\login\\index.js:120:20\n    at request.callback (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\service\\login\\index.js:150:17)"}}
[2017-08-09 16:10:40.214] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined","stack":"ReferenceError: D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:174:16)\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:325:10)\n    at returnedFn (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:520:17)\n    at View.exports.renderFile [as engine] (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:374:31)\n    at View.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\view.js:126:8)\n    at tryRender (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:639:10)\n    at EventEmitter.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:591:3)\n    at ServerResponse.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\response.js:960:7)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\routes\\web\\login\\index.js:120:20\n    at request.callback (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\service\\login\\index.js:150:17)"}}
[2017-08-09 16:10:41.263] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined","stack":"ReferenceError: D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:174:16)\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:325:10)\n    at returnedFn (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:520:17)\n    at View.exports.renderFile [as engine] (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:374:31)\n    at View.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\view.js:126:8)\n    at tryRender (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:639:10)\n    at EventEmitter.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:591:3)\n    at ServerResponse.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\response.js:960:7)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\routes\\web\\login\\index.js:120:20\n    at request.callback (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\service\\login\\index.js:150:17)"}}
[2017-08-09 16:10:42.110] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined","stack":"ReferenceError: D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:174:16)\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:325:10)\n    at returnedFn (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:520:17)\n    at View.exports.renderFile [as engine] (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:374:31)\n    at View.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\view.js:126:8)\n    at tryRender (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:639:10)\n    at EventEmitter.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:591:3)\n    at ServerResponse.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\response.js:960:7)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\routes\\web\\login\\index.js:120:20\n    at request.callback (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\service\\login\\index.js:150:17)"}}
[2017-08-09 16:10:42.325] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined","stack":"ReferenceError: D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:174:16)\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:325:10)\n    at returnedFn (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:520:17)\n    at View.exports.renderFile [as engine] (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:374:31)\n    at View.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\view.js:126:8)\n    at tryRender (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:639:10)\n    at EventEmitter.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:591:3)\n    at ServerResponse.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\response.js:960:7)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\routes\\web\\login\\index.js:120:20\n    at request.callback (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\service\\login\\index.js:150:17)"}}
[2017-08-09 16:11:04.064] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined","stack":"ReferenceError: D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\view.ejs:12\n    10|             <p class=\"header-nav\"><a href=\"/home\" class=\"dp-b fl-l\">首页</a>&nbsp;>&nbsp;<%= title %> </p>\r\n    11|             <div class=\"user-info\">\r\n >> 12|                 <%- include ./info.ejs %>\r\n    13|             </div>\r\n    14|         </div>\r\n    15|     </div>\r\n\nD:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\views\\agentCertification\\info.ejs:3\n    1| <% var lv; %>\r\n    2| <% var aLv; %>\r\n >> 3| <% switch (company.accountLevel) {\r\n    4|     case 0:\r\n    5|         lv = 'D';\r\n    6|         aLv = 'C';\r\n\ncompany is not defined\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:174:16)\n    at eval (eval at <anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:491:12), <anonymous>:325:10)\n    at returnedFn (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:520:17)\n    at View.exports.renderFile [as engine] (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\ejs\\lib\\ejs.js:374:31)\n    at View.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\view.js:126:8)\n    at tryRender (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:639:10)\n    at EventEmitter.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\application.js:591:3)\n    at ServerResponse.render (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\express\\lib\\response.js:960:7)\n    at D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\routes\\web\\login\\index.js:120:20\n    at request.callback (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\service\\login\\index.js:150:17)"}}
[2017-08-09 17:06:04.089] [ERROR] error - {"sid":-1,"ip":"::1","method":"GET","status":404}
[2017-08-09 17:06:04.901] [ERROR] error - {"sid":-1,"ip":"::1","method":"GET","status":404}
[2017-08-09 17:06:05.654] [ERROR] error - {"sid":-1,"ip":"::1","method":"GET","status":404}
[2017-08-09 17:06:11.281] [ERROR] error - {"sid":-1,"ip":"::1","method":"GET","status":404}
[2017-08-09 17:47:17.025] [ERROR] error - {"sid":-1,"ip":"::1","method":"GET","status":404}
[2017-08-09 17:49:24.090] [ERROR] error - {"sid":-1,"ip":"::1","method":"GET","status":404}
[2017-08-09 18:04:25.662] [ERROR] error - {"error":{"sid":-1,"method":"GET","url":"/login/Certification","message":"Redis connection lost and command aborted. It might have been processed.","stack":"AbortError: Redis connection lost and command aborted. It might have been processed.\n    at RedisClient.flush_and_error (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\redis\\index.js:350:23)\n    at RedisClient.connection_gone (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\redis\\index.js:652:14)\n    at RedisClient.on_error (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\redis\\index.js:398:10)\n    at Socket.<anonymous> (D:\\Desktop\\newversion\\NodeJs\\trunk\\KYB.Portal\\node_modules\\redis\\index.js:272:14)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1272:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)"}}
[2017-08-09 18:05:12.813] [ERROR] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:12.813] [FATAL] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:14.007] [ERROR] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:14.007] [FATAL] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:14.782] [ERROR] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:14.782] [FATAL] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:15.210] [ERROR] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:15.210] [FATAL] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:15.647] [ERROR] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:15.647] [FATAL] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:21.512] [ERROR] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:21.512] [FATAL] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:22.164] [ERROR] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:22.165] [FATAL] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:47.905] [ERROR] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:05:47.906] [FATAL] error - TypeError: Cannot set property 'fallback' of undefined
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\utils\gt3\index.js:30:38
    at D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:46:21
    at Request._callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\gt-sdk.js:76:17)
    at self.callback (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\Desktop\newversion\NodeJs\trunk\KYB.Portal\node_modules\gt3-sdk\node_modules\request\request.js:884:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:306:9)
[2017-08-09 18:44:44.750] [ERROR] error - {"sid":-1,"ip":"::1","method":"GET","status":404}
